### ISSUE TITLE
ModuleNotFoundError: No module named 'aardwolf'

### ISSUE THREAD

**Issue by init5-SF** [Pennyw0rth/NetExec#142]
**Describe the bug**
Using rdp throws a missing module error

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `./nxc rdp -L`
Resulted in:
```
Traceback (most recent call last):
  File "netexec.py", line 255, in <module>
  File "netexec.py", line 152, in main
  File "loaders/protocolloader.py", line 16, in load_protocol
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/_MEIPpQPnv/nxc/protocols/rdp.py", line 15, in <module>
    from aardwolf.connection import RDPConnection
ModuleNotFoundError: No module named 'aardwolf'
[3169] Failed to execute script 'netexec' due to unhandled exception!
```

**Expected behavior**
The available rdp modules should be listed (if any)

**Screenshots**
![image](https://github.com/Pennyw0rth/NetExec/assets/10214861/0025019c-d324-4c14-8c7d-c5ebe3c82bef)

**NetExec info**
 - OS: Kali
 - Python: 3.11.6
 - Version of nxc: 1.1.0
 - Installed from: Using the standalone binary - https://github.com/Pennyw0rth/NetExec/releases/download/v1.1.0/nxc

**Comment by NeffIsBack** [comment]
Hi, thanks for the bug report, but there already exist an issue for this #84
