### ISSUE TITLE
download error by pipx in linux

### ISSUE THREAD

**Issue by rightevil** [Pennyw0rth/NetExec#197]
the error:
```
proxychains pipx install git+https://github.com/Pennyw0rth/NetExec
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
  error: subprocess-exited-with-error
  
  × Building wheel for netexec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      [proxychains] DLL init: proxychains-ng 4.17
      Traceback (most recent call last):
        File "/home/rightevil/.local/share/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rightevil/.local/share/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rightevil/.local/share/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 124, in build
          self._copy_module(zip_file)
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 265, in _copy_module
          to_add = self.find_files_to_add()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 223, in find_files_to_add
          if self.is_excluded(
             ^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 153, in is_excluded
          if exclude_path.as_posix() in self.find_excluded_files(fmt=self.format):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 121, in find_excluded_files
          vcs_ignored_files = set(vcs.get_ignored_files()) if vcs else set()
                                  ^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/vcs/git.py", line 340, in get_ignored_files
          output = self.run(*args)
                   ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n9hjhvai/overlay/lib/python3.11/site-packages/poetry/core/vcs/git.py", line 373, in run
          subprocess.check_output(
        File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', '--git-dir', '[proxychains] DLL init: proxychains-ng 4.17\n/tmp/pip-req-build-i4scwu9d/.git', '--work-tree', '[proxychains] DLL init: proxychains-ng 4.17\n/tmp/pip-req-build-i4scwu9d', 'ls-files', '--others', '-i', '--exclude-standard']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for netexec
ERROR: Could not build wheels for netexec, which is required to install pyproject.toml-based projects
Cannot determine package name from spec 'git+https://github.com/Pennyw0rth/NetExec'. Check package spec for errors.

```

**Comment by XiaoliChan** [comment]
Looks like some weird issues caused by proxychains.

**Comment by rightevil** [comment]
> Looks like some weird issues caused by proxychains, can you try to install without proxychains?
it's hard cause the internet.we couldn't connect github directly.if the reason of error was proxychains,pls closed the problem
```
pipx install git+https://github.com/Pennyw0rth/NetExec
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/Pennyw0rth/NetExec /tmp/pip-req-build-82xn28x8 did not run successfully.
  │ exit code: 128
  ╰─> [1 lines of output]
      致命错误：无法访问 'https://github.com/Pennyw0rth/NetExec/'：GnuTLS recv error (-110): TLS 链接非正常地终止了。
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Pennyw0rth/NetExec /tmp/pip-req-build-82xn28x8 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec 'git+https://github.com/Pennyw0rth/NetExec'. Check package spec for errors.
```

**Comment by XiaoliChan** [comment]
If you're a Chinese user, can you try this?

https://github.com/L-codes/LTProxy
