### ISSUE TITLE
ModuleNotFoundError: No module named 'impacket.dcerpc.v5.gkdi'

### ISSUE THREAD

**Issue by AkechiShiro** [Pennyw0rth/NetExec#397]
**Describe the bug**
ModuleNotFoundError: No module named 'impacket.dcerpc.v5.gkdi' when running 
```
nxc smb <ip-range> -u 'a' -p '' --shares
```

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `nxc smb 192.168.1.10-23 -u 'a' -p '' --shares`
Resulted in:
```
Traceback (most recent call last):
  File "/usr/bin/nxc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/nxc/netexec.py", line 143, in main
    protocol_object = getattr(p_loader.load_protocol(protocol_path), args.protocol)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nxc/loaders/protocolloader.py", line 16, in load_protocol
    loader.exec_module(protocol)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/nxc/protocols/smb.py", line 32, in <module>
    from nxc.connection import connection, sem, requires_admin, dcom_FirewallChecker
  File "/usr/lib/python3/dist-packages/nxc/connection.py", line 15, in <module>
    from nxc.protocols.ldap.laps import laps_search
  File "/usr/lib/python3/dist-packages/nxc/protocols/ldap/laps.py", line 11, in <module>
    from impacket.dcerpc.v5.gkdi import MSRPC_UUID_GKDI, GkdiGetKey, GroupKeyEnvelope
ModuleNotFoundError: No module named 'impacket.dcerpc.v5.gkdi'
```

**Expected behavior**
Should work.

**Screenshots**

**NetExec info**
 - OS: [e.g. Kali] Kali Linux 
 - Version of nxc: [e.g. v1.5.2] 1.2.0 - ItsAlwaysDNS - kali
 - Installed from: apt 
 
**Additional context**
I also have Nix as a package manager installed.

**Comment by AkechiShiro** [comment]
I had `impacket 0.11` installed locally, after removing it, everything worked as intended.

**Comment by 12345qwert123456** [comment]
If you don't want to remove impacket, you can try the following method:

1. Remove the **pre-installed** netexec: `sudo apt remove netexec`
2. Install it using **pipx**: `pipx install git+https://github.com/Pennyw0rth/NetExec`

And everything should work.
