### ISSUE TITLE
No package metadata was found for netexec

### ISSUE THREAD

**Issue by secure-77** [Pennyw0rth/NetExec#51]
Executing the latest build will fail with an PackageNotFoundError

**To Reproduce**
Download the latest build from actions: [nxc-ubuntu-latest-3.11](https://github.com/Pennyw0rth/NetExec/suites/16713099302/artifacts/955084659)

Run it with the following command: `./nxc smb 10.10.121.244 -u 'test' -p 'test'`
Resulted in:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sec/./nxc/__main__.py", line 3, in <module>
  File "/home/sec/./nxc/_bootstrap/__init__.py", line 253, in bootstrap
  File "/home/sec/./nxc/_bootstrap/__init__.py", line 38, in run
  File "/home/sec/.shiv/nxc_aecf6c0b8a0cbcd1f5679edf2b69e9c2008a4c3700c4a451aea1d3f78207456c/site-packages/nxc/netexec.py", line 80, in main
    args = gen_cli_args()
           ^^^^^^^^^^^^^^
  File "/home/sec/.shiv/nxc_aecf6c0b8a0cbcd1f5679edf2b69e9c2008a4c3700c4a451aea1d3f78207456c/site-packages/nxc/cli.py", line 15, in gen_cli_args
    VERSION = importlib.metadata.version("netexec")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for netexec
```

**NetExec info**
 - OS: Kali
 - Version of nxc [latest]
 - Installed from: Actions

**Comment by Marshall-Hallenbeck** [comment]
@secure-77 We're still testing before releasing v1.0.0, so don't use anything from the recent builds - only stuff in releases (when we get there).

As for running that anyway, it's a Python zipapp, so you have to run it with Python, e.g. `python nxc smb...`

**Comment by secure-77** [comment]
thx for the response!

I get the same error when running it with python:

![image](https://github.com/Pennyw0rth/NetExec/assets/31564517/2b61b87f-809c-4116-b74f-8ffe5fefd19e)



 however, the docker image is working fine, so I will use this until release 👍

**Comment by Marshall-Hallenbeck** [comment]
@secure-77 Roger, I'll look into that, thanks!
