### ISSUE TITLE
ImportError on NixOS

### ISSUE THREAD

**Issue by Serif-7** [Pennyw0rth/NetExec#518]
**Describe the bug**

```
Traceback (most recent call last):
  File "/nix/store/ybb98wjdyf2a9pj5rzwby58dmxpai6w1-netexec-1.1.0-unstable-2024-01-15/bin/.netexec-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/ybb98wjdyf2a9pj5rzwby58dmxpai6w1-netexec-1.1.0-unstable-2024-01-15/lib/python3.12/site-packages/nxc/netexec.py", line 152, in main
    protocol_object = getattr(p_loader.load_protocol(protocol_path), args.protocol)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ybb98wjdyf2a9pj5rzwby58dmxpai6w1-netexec-1.1.0-unstable-2024-01-15/lib/python3.12/site-packages/nxc/loaders/protocolloader.py", line 16, in load_protocol
    loader.exec_module(protocol)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/ybb98wjdyf2a9pj5rzwby58dmxpai6w1-netexec-1.1.0-unstable-2024-01-15/lib/python3.12/site-packages/nxc/protocols/smb.py", line 59, in <module>
    from pywerview.cli.helpers import get_localdisks, get_netsession, get_netgroupmember, get_netgroup, get_netcomputer, get_netloggedon, get_netlocalgroup
  File "/nix/store/zcaqgk9rflz1w368402b0qb32kaqxrzq-python3.12-pywerview-0.7.1/lib/python3.12/site-packages/pywerview/cli/helpers.py", line 20, in <module>
    from pywerview.functions.net import NetRequester
  File "/nix/store/zcaqgk9rflz1w368402b0qb32kaqxrzq-python3.12-pywerview-0.7.1/lib/python3.12/site-packages/pywerview/functions/net.py", line 29, in <module>
    from impacket.ldap.ldaptypes import LDAP_SERVER_SD_FLAGS, LDAP_SID, SR_SECURITY_DESCRIPTOR
ImportError: cannot import name 'LDAP_SERVER_SD_FLAGS' from 'impacket.ldap.ldaptypes' (/nix/store/1nf3572rwqc1vpynqirhfc5007q232rq-python3.12-impacket-0.12.0.dev1-unstable-2023-11-30/lib/python3.12/site-packages/impacket/ldap/ldaptypes.py)
```
Command: `netexec smb 10.129.112.245 --shares -u '' -p ''`

System: NixOS 25.05, unstable

**Comment by NeffIsBack** [comment]
Hi, how did you install NetExec?

**Comment by Serif-7** [comment]
@NeffIsBack installed it declaratively via Home Manager. Source is here: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/security/netexec/default.nix#L96

Unfortunately I'm not great at reading Nix package files or I could fix this myself.

**Comment by NeffIsBack** [comment]
Hmm ok. We do not Package the package for the distros ourselves, so we can't fix what is broken. We highly recommend using pipx though. That is stable and uses the newest commits.
See: https://www.netexec.wiki/getting-started/installation/installation-on-unix

**Comment by Serif-7** [comment]
I'll try that. Also emailed the maintainer requesting an update.
