### ISSUE TITLE
(WIN BIN) aardwof missing

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#84]
Traceback (most recent call last):
  File "netexec.py", line 276, in <module>
  File "netexec.py", line 162, in main
  File "loaders\protocolloader.py", line 18, in load_protocol
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\mrpoopypants\AppData\Local\Temp\_MEI112922\nxc\protocols\rdp.py", line 18, in <module>
    from aardwolf.connection import RDPConnection
ModuleNotFoundError: No module named 'aardwolf'
[4176] Failed to execute script 'netexec' due to unhandled exception!

**Comment by Marshall-Hallenbeck** [comment]
What command did you use to get this error?

**Comment by bongobongoland** [comment]
nxc.exe rdp IP -u user -p pass

**Comment by bongobongoland** [comment]
![image](https://github.com/Pennyw0rth/NetExec/assets/129246896/5bd7faee-bb3b-4ae2-a49c-843dff5b681f)
